project_story/urls.py
from django.contrib import admin
from django.urls import include, path
from story4.views import profile

urlpatterns = [
    path('', profile, name='profile'),
    path('admin/', admin.site.urls),
    path('story4/', include('story4.urls')),
]

story4/urls.py
from django.urls import include, path

from .views import *

app_name = 'story4'

urlpatterns = [
    path('', profile, name='profile'),
    path('desc/', desc, name='desc'),
    path('story1/', story1, name='story1'),
    path('addmatkul/', AddMatkul, name = 'addmatkul'),
    path('addmatkul/savematkul/', SaveMatkul, name = 'savematkul'),
    path('viewmatkul/', ViewMatkul, name = 'viewmatkul'),
    path('viewmatkul/<int:id_matkul>/', ClearMatkul, name = 'clearmatkul'),
    path('viewmatkul/detail/<int:id_matkul>/', DetailMatkul, name = 'detailmatkul'),
    path('addkegiatan/', AddKegiatan, name = 'addkegiatan'),
    path('addkegiatan/savekegiatan/', SaveKegiatan, name = 'savekegiatan'),
    path('viewkegiatan/', ViewKegiatan, name = 'viewkegiatan'),
    path('viewkegiatan/addpeserta/<int:id_kegiatan>/', AddPeserta, name = 'addpeserta'),
    path('viewkegiatan/addpeserta/<int:id_kegiatan>/savepeserta/', SavePeserta, name = 'savepeserta'),
    path('viewkegiatan/clear/', ClearKegiatan, name = 'clearkegiatan'),
    path('accordion/', accordion, name = 'accordion'),
    path('search/', search, name = 'search')
    ]

story4/models.py
from django.db import models

class MataKuliah(models.Model):
    nama_matkul = models.CharField(max_length=50)
    nama_dosen = models.CharField(max_length=50)
    jumlah_sks = models.CharField(max_length=50)
    deskripsi_matkul = models.CharField(max_length=50)
    semester = models.CharField(max_length=50)
    ruang_kelas = models.CharField(max_length=50)

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=50)

class Peserta(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    nama_peserta = models.CharField(max_length=50)

class KegiatanTemp:
    def __init__(self, id, nama, list_peserta):
        self.id = id
        self.nama = nama
        self.list_peserta = list_peserta

story4/forms.py
from django import forms
from .models import MataKuliah

class CreateMatkul(forms.Form):
    attr = {
        'type': 'text',
        'class': 'form-control',
    }

    nama_matkul = forms.CharField(label='Nama Mata Kuliah', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))
    nama_dosen = forms.CharField(label='Nama Dosen', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))
    jumlah_sks = forms.CharField(label='Jumlah SKS', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))
    deskripsi_matkul = forms.CharField(label='Deskripsi', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))
    semester = forms.CharField(label='Semester', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))
    ruang_kelas = forms.CharField(label='Ruang Kelas', max_length=50,  required=True, widget=forms.TextInput(attrs=attr))

class CreateKegiatan(forms.Form):
    attr = {
        'type': 'text',
        'class': 'form-control',
    }

    nama_kegiatan = forms.CharField(label='Nama Kegiatan', max_length=50, required=True, widget=forms.TextInput(attrs=attr))

class CreatePeserta(forms.Form):
    attr = {
        'type': 'text',
        'class': 'form-control',
    }

    nama_peserta = forms.CharField(label='Nama Peserta', max_length=50, required=True, widget=forms.TextInput(attrs=attr))

class SearchForm(forms.Form):
	attr = {
	    'type' : 'query',
	    'class' : 'form-control',
	    'placeholder' : '...',
	    'id' : 'search-name'
	}

	nama_buku = forms.CharField(max_length=300, label="Masukkan kata pencari", required=False, widget=forms.TextInput(attrs=attr))

story4/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect, request
from .forms import CreateMatkul, CreateKegiatan, CreatePeserta, SearchForm
from .models import MataKuliah, Kegiatan, Peserta, KegiatanTemp

def profile(request):
    return render (request, 'profile.html')

def desc(request):
    return render (request, 'desc.html')

def story1(request):
    return render (request, 'story1.html')

def AddMatkul(request):
    response = {'create_matkul' : CreateMatkul}
    return render (request, 'addmatkul.html', response)

def SaveMatkul(request):
    response = {'save_status':''}
    if (request.method == 'POST'):
        form = CreateMatkul(request.POST)
        if (form.is_valid()):
            nama_matkul = form.cleaned_data['nama_matkul'] 
            nama_dosen = form.cleaned_data['nama_dosen'] 
            jumlah_sks = form.cleaned_data['jumlah_sks']
            deskripsi_matkul = form.cleaned_data['deskripsi_matkul'] 
            semester = form.cleaned_data['semester'] 
            ruang_kelas = form.cleaned_data['ruang_kelas']

            matkul = MataKuliah(
                nama_matkul = nama_matkul,
                nama_dosen = nama_dosen,
                jumlah_sks = jumlah_sks,
                deskripsi_matkul = deskripsi_matkul,
                semester = semester,
                ruang_kelas = ruang_kelas

            )

            matkul.save()

            response['save_status'] = 'Mata kuliah berhasil ditambahkan'
        else:
            response['save_status'] = 'Mata kuliah gagal ditambahkan'
    else:
        response['save_status'] = 'Something went wrong'

    return render (request, 'save.html', response)

def ViewMatkul(request):
    list_matkul = MataKuliah.objects.all().values()
    response = {'list_matkul' : list_matkul}
    return render (request, 'viewmatkul.html', response)

def ClearMatkul(request, id_matkul = None):
    list_matkul = MataKuliah.objects.all().values()
    MataKuliah.objects.get(id=id_matkul).delete()
    response = {'list_matkul':list_matkul}
    return HttpResponseRedirect('/story4/viewmatkul/')

def DetailMatkul(request, id_matkul = None):
    matkul = MataKuliah.objects.get(id=id_matkul)
    response = {'matkul':matkul}
    return render (request, 'detailmatkul.html', response)

def AddKegiatan(request):
    response = {'create_kegiatan' : CreateKegiatan}
    return render (request, 'addkegiatan.html', response)

def SaveKegiatan(request):
    response = {'save_status':''}
    if (request.method == 'POST'):
        form = CreateKegiatan(request.POST)
        if (form.is_valid()):
            nama_kegiatan = form.cleaned_data['nama_kegiatan']

            kegiatan = Kegiatan(
                nama_kegiatan = nama_kegiatan
            )

            kegiatan.save()
        
            response['save_status'] = 'Kegiatan berhasil ditambahkan'
        else:
            response['save_status'] = 'Kegiatan gagal ditambahkan'
    else:
        response['save_status'] = 'Something went wrong'

    return render (request, 'save.html', response)

def ViewKegiatan(request):
    kegiatan_temp = []
    list_kegiatan = Kegiatan.objects.all().values()
    for kegiatan in list_kegiatan:
        list_peserta = Peserta.objects.filter(kegiatan=Kegiatan.objects.get(id=kegiatan['id']))
        kegiatan_temp.append(KegiatanTemp(kegiatan['id'], kegiatan['nama_kegiatan'], list_peserta))
    response = {'list_kegiatan' : kegiatan_temp}
    return render (request, 'viewkegiatan.html', response)

def AddPeserta(request, id_kegiatan = None):
    response = {'create_peserta' : CreatePeserta, 'id_kegiatan' : id_kegiatan}
    return render (request, 'addpeserta.html', response)

def SavePeserta(request, id_kegiatan = None):
    response = {'save_status':''}
    if (request.method == 'POST'):
        form = CreatePeserta(request.POST)
        if (form.is_valid()):
            nama_peserta = form.cleaned_data['nama_peserta']
            peserta = Peserta(
                nama_peserta = nama_peserta,
                kegiatan = Kegiatan.objects.get(id=id_kegiatan)
            )

            peserta.save()
        
            response['save_status'] = 'Peserta berhasil ditambahkan'
        else:
            response['save_status'] = 'Peserta gagal ditambahkan'
    else:
        response['save_status'] = 'Something went wrong'

    return render (request, 'save.html', response)

def ClearKegiatan(request):
    list_kegiatan = Kegiatan.objects.all().values()
    Kegiatan.objects.all().delete()
    response = {'list_kegiatan':list_kegiatan}
    return HttpResponseRedirect('/story4/viewkegiatan/')

def accordion(request):
    return render (request, 'accordion.html')

def search(request):
    response = {"SearchForm" : SearchForm}
    return render(request, "searchbox.html", response)

story4/templates/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'sortableaccordion.js' %}"></script>
{% endblock %}

{% block content %}
<div id="accordion">
    <div class="group">
      <h3>Aktivitas saat ini</h3>
      <div>
        <p>Saat ini, saya adalah seorang mahasiswa yang sering menghabiskan waktu saya untuk mencari tahu tentang banyak hal (walaupun biasanya tidak terkait dengan materi perkuliahan :/) dan mendengarkan lagu. Saya juga sering
           menggunakan waktu kosong saya untuk bermain game bersama teman-teman seangkatan ketika sedang jenuh dengan banyaknya tugas yang ada.
        </p>
      </div>
    </div>
    <div class="group">
      <h3>Pengalaman organisasi/kepanitiaan</h3>
      <div>
        <ul>
            <li>Divisi acara pentas seni 'Gado-gado' SMAN 39 Jakarta</li>
            <li>Tim pengajar Teknik Informal School (TIS) FTUI</li>
        </ul>
      </div>
    </div>
    <div class="group">
      <h3>Prestasi</h3>
      <div>
        <p>Sebenarnya, saya merasa bahwa saya belum memiliki prestasi yang pantas untuk disebutkan sebagai 'prestasi' :) <br> Bagian ini hanya berfungsi untuk mengisi kolom dari accordion ini</p>
        <ul>
          <li>Ini prestasi pertama</li>
          <li>Ini prestasi kedua</li>
          <li>Ini prestasi ketiga</li>
        </ul>
      </div>
    </div>
    <div class="group">
      <h3>Harapan tentang PPW</h3>
      <div>
        <p>Saat ini, saya akan merasa senang jika saya mampu menyelesaikan kuliah PPW dengan nilai lulus, berapapun nilainya. Saya berharap saya mampu mengikuti materi-materi yang ada hingga 
           akhir semester dengan baik dan dapat membawa ilmu yang saya peroleh pada kuliah ini hingga setelah lulus nanti</p>
      </div>
    </div>
  </div>
{% endblock %}

story4/templates/addkegiatan.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class='row'>
        <div class='col'>
            <h1>Tambahkan Kegiatan</h1>
        </div>
    </div>

    <div class='row'>
        <div class='col'>
            <form action="savekegiatan/" method="POST">
                <div class="form-group">
                    {% csrf_token %}

                    {{ create_kegiatan }}
                </div>
                <button type="submit" class="btn btn-dark">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

story4/templates/addmatkul.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class='row'>
        <div class='col'>
            <h1>Tambahkan Mata Kuliah</h1>
        </div>
    </div>

    <div class='row'>
        <div class='col'>
            <form action="savematkul/" method="POST">
                <div class="form-group">
                    {% csrf_token %}

                    {{ create_matkul }}
                </div>
                <button type="submit" class="btn btn-dark">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

story4/templates/addpeserta.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class='row'>
        <div class='col'>
            <h1>Tambahkan Peserta</h1>
        </div>
    </div>

    <div class='row'>
        <div class='col'>
            <form action="savepeserta/" method="POST">
                <div class="form-group">
                    {% csrf_token %}

                    {{ create_peserta }}
                </div>
                <button type="submit" class="btn btn-dark">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

story4/templates/base.html
<!DOCTYPE html>
<html>

<head>
<title>My Profile Page</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="{% static 'style.css' %}" />
{% block head %}
{% endblock %}
</head>

<body>
<div class="header">
    <h1>My Profile Page</h1>
    <p>Masih belum rapi - tunggu beberapa minggu lagi :)</p>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:desc' %}">Description</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:story1' %}">Story 1</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:addmatkul' %}">Tambah Matkul</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:viewmatkul' %}">Lihat Matkul</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:addkegiatan' %}">Tambah Kegiatan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:viewkegiatan' %}">Lihat Kegiatan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:accordion' %}">Story 7</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story4:search' %}">Story 8</a>
        </li>
      </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

story4/templates/desc.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="single-grid-1">
        <h2>Deskripsi</h2>
        <p>Mahasiswa yang terlihat biasa saja tapi ingin berhenti menjadi biasa saja.<br>
           Memiliki motto hidup <i>Be yourself and never surrender.</i></p><br>
           Sejak dulu, mimpi saya seringkali berubah seiring waktu. Pada saat kecil, saya memiliki keinginan untuk menjadi dokter untuk membantu banyak orang. Selang 
           beberapa lama, saya pun berkeinginan untuk menjadi seorang <br> insinyur karena terkesima dengan lingkungan pekerjaan ayah saya.<br><br>
           Mimpi saya memang sering berubah-ubah. Akan tetapi, saat ini saya memiliki sebuah keinginan yang lebih besar dari sebelumnya; Menjadi seorang programmer yang hebat
           dan menjadi seseorang yang mampu mengatasi <br> masalah apapun. Kali ini, keinginan itu berasal dari dalam diri saya sendiri.</p>
    </div>
</div>

<div class="row">
    <div class="single-grid-2">
        <h2>Riwayat Pendidikan</h2>
        <dl>
            <dt style="margin-top: 2px;">Sekolah Dasar:</dt>
                <dd>SD Islam PB Soedirman, Jakarta Timur (2008-2013)<br>
                - Mengikuti program akselerasi
                </dd>
            <dt style="margin-top: 2px;">Sekolah Menengah Pertama:</dt>
                <dd>SMP Islam PB Soedirman, Jakarta Timur (2013-2015)<br>
                - Mengikuti program akselerasi
                </dd>
            <dt style="margin-top: 2px;">Sekolah Menengah Atas:</dt>
                <dd>SMA Negeri 39 Jakarta (2015-2018)</dd>
            <dt style="margin-top: 2px;">Perguruan Tinggi:</dt>
                <dd>1. Fakultas Teknik Universitas Indonesia (2018-2019)<br>
                - Jurusan Teknik Elektro</dd>
                <dd>2. Fakultas Ilmu Komputer Universitas Indonesia (2019-2020)<br>
                - Jurusan Ilmu Komputer</dd>
        </dl>
    </div>
</div>
{% endblock %}

story4/templates/detailmatkul.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col"><h1>Detail Mata Kuliah</h1></div>
    </div>
    
    <div class="row">
        <div class="col">
            <p>Nama Mata Kuliah:</p>
            <p>{{ matkul.nama_matkul }}</p>
            <p>Nama Dosen:</p>
            <p>{{ matkul.nama_dosen }}</p>
            <p>Jumlah SKS:</p>
            <p>{{ matkul.jumlah_sks }}</p>
            <p>Deskripsi:</p>
            <p>{{ matkul.deskripsi_matkul }}</p>
            <p>Semester:</p>
            <p>{{ matkul.semester }}</p>
            <p>Ruang Kelas</p>
            <p>{{ matkul.ruang_kelas }}</p>
            <a href="{% url 'story4:viewmatkul' %}" class="btn btn-secondary">Kembali</a>
        </div>
    </div>

    

</div>
{% endblock %}

story4/templates/profile.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="side">
        <h2>All about me</h2>
        <img src= {% static 'DaffaElGhifari.jpg' %} alt="Foto ganteng" width="200">
            <p><a href="https://instagram.com/delghifari_">Instagram</a></p>
            <p><a href="https://twitter.com/elschifff">Twitter</a></p>
    </div>

    <div class="main" style="height: 800px;">
        <h2>Welcome!</h2>

        <p>Nama: Mochammed Daffa El Ghifari</p>
        <p>TTL: Jakarta, 26 Juni 2002</p>
        <p>NPM: 1906350976</p>
        <p>Status: Mahasiswa</p>
        <p>Tempat Kuliah: Fakultas Ilmu Komputer Universitas Indonesia</p>
        <p>Angkatan: Maung (2019)</p>
        <p>Hobi: Tenis meja, video game</p>

    </div>

</div>
{% endblock %}

story4/templates/save.html
{% extends 'base.html' %}

{% block content %}
<h1>
    {{ save_status }}
</h1>
{% endblock %}

story4/templates/searchbox.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'search.js' %}"></script>
{% endblock %}

{% block content %}

<div class="container-fluid">
	<h1 class="mt-5 offset-1">Search Book</h1>
	<form id="search-form">
		<div class="offset-1">
			<div class="form-group">
				{% csrf_token %}

				{{SearchForm}}
			</div>
		</div>
		<div class="offset-1 align-content-end">
			<button class="btn btn-primary" id="button-search">Search</button>
		</div>
	</form>
	<div class="row">
		<table class="table table-responsive table-hover mt-5">
			<thead class="table-header">
				<tr>
					<th scope="col">Nama</th>
					<th scope="col">Gambar</th>
					<th scope="col">Deskripsi</th>
					<th scope="col">Penulis</th>
				</tr>
			</thead>
			<tbody id="books"></tbody>
		</table>
	</div>

</div>
</body>
</html>
{% endblock %}

story4/templates/story1.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h2>Welcome!</h2>

<img src={% static 'DaffaElGhifari.jpg' %} alt="Foto ganteng" width="300"> 

<p>Nama: Mochammed Daffa El Ghifari</p>
<p>TTL: Jakarta, 26 Juni 2002</p>
<p>NPM: 1906350976</p>
<p>Angkatan: Maung</p>
<p>Hobi: Tenis meja, video game</p>
<p>Deskripsi: Mahasiswa yang terlihat biasa saja tapi sedang ingin berhenti menjadi biasa saja.<br> 
          Memiliki motto hidup <i>Be yourself and never surrender</i></p>
<p>Tempat Kuliah: Fakultas Ilmu Komputer Universitas Indonesia</p>

<p>Riwayat Pendidikan:</p>
<dl>
<dt style="margin-top: 2px;">Sekolah Dasar:</dt>
    <dd>SD Islam PB Soedirman, Jakarta Timur (2008-2013)<br>
    - Mengikuti program akselerasi
    </dd>
<dt style="margin-top: 2px;">Sekolah Menengah Pertama:</dt>
    <dd>SMP Islam PB Soedirman, Jakarta Timur (2013-2015)<br>
    - Mengikuti program akselerasi
    </dd>
<dt style="margin-top: 2px;">Sekolah Menengah Atas:</dt>
    <dd>SMA Negeri 39 Jakarta (2015-2018)</dd>
<dt style="margin-top: 2px;">Perguruan Tinggi:</dt>
    <dd>1. Fakultas Teknik Universitas Indonesia (2018-2019)<br>
    - Jurusan Teknik Elektro</dd>
    <dd>2. Fakultas Ilmu Komputer Universitas Indonesia (2019-2020)<br>
    - Jurusan Ilmu Komputer</dd>
</dl>

<p>Media Sosial:</p>
<ul>
<li>Instagram: <a href="https://instagram.com/delghifari_">@delghifari_</a></li>
</ul>
{% endblock %}

story4/templates/viewkegiatan.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col m-2"><h1>Daftar Kegiatan</h1></div>
    </div>
    
        {% if list_kegiatan %}
        {% for kegiatan in list_kegiatan %}
        <div class="row m-2 border-dark">
            <div class="col">
                <p>{{kegiatan.nama}}</p>
                <ul>
                {% for peserta in kegiatan.list_peserta %}
                <li><p>{{peserta.nama_peserta}}</p></li>
                {% endfor %}    
                </ul>
            </div>

            <div class="col"><a class = "btn btn-danger" href = "{% url 'story4:addpeserta' kegiatan.id %}" role = "button"><p>Tambah Peserta</p></a></div>
        </div>

        {% endfor %}

        <div class="col my-5 mx-2"><a class = "btn btn-secondary" href = "{% url 'story4:clearkegiatan' %}" role = "button"><p>Hapus Semua Kegiatan</p></a></div>

        {% else %}
        <h4>Daftar kegiatan masih kosong, tambah kegiatan terlebih dahulu!</h4>

        {% endif %}

</div>
{% endblock %}

story4/templates/viewmatkul.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col"><h1>Daftar Mata Kuliah</h1></div>
    </div>
    
    <div class="row">
        <div class="col"><p>Nama Matkul</p></div>
    </div>


    {% for matkul in list_matkul %}
    <div class="row mb-1">
        <div class="col"><p>{{ matkul.nama_matkul }}</p></div>
        <div class="col"><a class = "btn btn-secondary" href = "{% url 'story4:detailmatkul' matkul.id %}" role = "button"><p>Detail</p></a></div>
        <div class="col"><a class = "btn btn-danger" href = "{% url 'story4:clearmatkul' matkul.id %}" role = "button"><p>Hapus</p></a></div>
    </div>
    {% endfor %}
    

</div>
{% endblock %}